# Generated by Django 5.1.3 on 2024-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('United_in_Rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.CharField(max_length=100),
        ),
    ]
