# Generated by Django 5.1.3 on 2024-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('United_in_Rights', '0002_alter_client_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(max_length=100)),
                ('victim_email', models.CharField(max_length=100)),
                ('contact_subject', models.CharField(max_length=100)),
                ('victim_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
