# Generated by Django 5.1.3 on 2024-12-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('United_in_Rights', '0003_victim_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
