# Generated by Django 5.1.3 on 2024-12-12 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('United_in_Rights', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='victim_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
